#!/usr/bin/env python

"""Amulet tests on a basic aodh deployment on xenial-ocata."""

from basic_deployment import GlusterFSBasicDeployment

if __name__ == '__main__':
    deployment = GlusterFSBasicDeployment(series='xenial',
                                          openstack='cloud:xenial-pike')
deployment.run_tests()
